INSERT INTO TAG (NAME) VALUES ('Big');
INSERT INTO TAG (NAME) VALUES ('Small');
INSERT INTO TAG (NAME) VALUES ('Gilss');
INSERT INTO TAG (NAME) VALUES ('Active');

INSERT INTO CATEGORY (NAME) VALUES ('Dog');
INSERT INTO CATEGORY (NAME) VALUES ('Cat');
INSERT INTO CATEGORY (NAME) VALUES ('Bird');
INSERT INTO CATEGORY (NAME) VALUES ('Fish');